---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: wbitt/network-multitool
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 250m
              memory: 125Mi
            limits:
              cpu: 500m
              memory: 250Mi

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 8080
  type: ClusterIP
