---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_PORT
              value: "8080"
          volumeMounts:
          - name: volume
            mountPath: /nfs-storage
          resources:
            requests:
              cpu: 250m
              memory: 125Mi
            limits:
              cpu: 500m
              memory: 250Mi
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: nfs-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-storage
spec:
  storageClassName: nfs-csi
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
