---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: custom-web-page
              mountPath: /var/www/mypage
            - name: my-nginx-conf
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              cpu: 250m
              memory: 125Mi
            limits:
              cpu: 500m
              memory: 250Mi
          ports:
            - containerPort: 80
        - name: multitool
          image: wbitt/network-multitool
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HTTP_PORT
          resources:
            requests:
              cpu: 250m
              memory: 125Mi
            limits:
              cpu: 500m
              memory: 250Mi
      volumes:
        - name: custom-web-page
          configMap:
            name: my-configmap
            items:
            - key: CUSTOM_WEB_PAGE
              path: custom.html
        - name: my-nginx-conf
          configMap:
            name: my-configmap
            items:
            - key: NGINX_CONF
              path: default.conf

---
apiVersion: v1
kind: Service
metadata:
  name: kunaev-svc
spec:
  selector:
    app: myapp
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080
  type: ClusterIP

