---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: multitool
spec:
  containers:
  - name: standalone-multitool
    image: wbitt/network-multitool
    imagePullPolicy: IfNotPresent
    env:
      - name: HTTP_PORT
        value: "8080"
    resources:
      requests:
        cpu: 250m
        memory: 125Mi
      limits:
        cpu: 500m
        memory: 250Mi